services:
  - type: web
    name: lien-quan-tournament
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://Giaidauienquan:sanggot123456@cluster0.bm5ghwp.mongodb.net/lien-quan-tournament?retryWrites=true&w=majority
      - key: SESSION_SECRET
        value: your-secret-key-123456789
      - key: ADMIN_EMAIL
        value: admin@tournament.local
      - key: ADMIN_PASSWORD
        value: 12345678
